version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: Greenweez ham verileri
    
    # Tazelik Testi (Freshness) - Veri 90 günden eskiyse uyarır
    loaded_at_field: "CAST(date_date AS TIMESTAMP)"
    freshness:
      warn_after: {count: 90, period: day}

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Greenweez satış verileri / her siparişteki (orders_id) her ürün (products_id) için bir satır.
        columns:
          - name: date_date
            description: satın alma tarihi
          - name: orders_id
            description: sipariş numarası (ship tablosuna foreign key)
          - name: pdt_id
            description: ürün numarası (product tablosuna foreign key)
          - name: revenue
            description: müşterinin ürün için ödediği tutar. ciro = miktar * satış_fiyatı
          - name: quantity
            description: siparişteki ürün adedi
        tests:
          # Composite Key Testi: Aynı siparişte aynı ürün iki kere olamaz.
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: Greenweez ürün kataloğu
        columns:
          - name: products_id
            description: Birincil anahtar (Primary Key)
          - name: purchase_price
            description: ürünün alış fiyatı
        tests:
          - unique:
              column_name: products_id
          - not_null:
              column_name: products_id

      - name: ship
        identifier: raw_gz_ship
        description: Greenweez siparişleri için kargo verileri
        columns:
          - name: orders_id
            description: Birincil anahtar (Primary Key)
          - name: shipping_fee
            description: müşterinin kargo için ödediği tutar
          - name: log_cost
            description: dağıtım merkezinde paketi hazırlama maliyeti
          - name: ship_cost
            description: kargo firmasına ödenen taşıma maliyeti
        tests:
          - unique:
              column_name: orders_id
          - not_null:
              column_name: orders_id