version: 2

sources:
  - name: raw                # dbt içinde kullanacağımız veri kümesi adı (takma ad)
    schema: gz_raw_data      # BigQuery'deki GERÇEK veri kümesi adı
    tables:
      - name: sales          # dbt içinde kullanacağımız tablo adı
        identifier: raw_gz_sales  # BigQuery'deki GERÇEK tablo adı
      
      - name: product
        identifier: raw_gz_product
      
      - name: ship
        identifier: raw_gz_ship